---
- hosts:
  - proxy
  - jupyterhub_host
  - jupyterhub_nodes
  vars_files:
  - 'secrets.vault.yml'
  - 'vars.yml'
  roles:
  - common

- hosts:
  - jupyterhub_host
  - jupyterhub_nodes
  vars_files:
  - 'secrets.vault.yml'
  - 'vars.yml'
  roles:
  - docker

- hosts: proxy
  vars_files:
  - 'secrets.vault.yml'
  - 'vars.yml'
  roles:
  - proxy

- hosts:
  - jupyterhub_host
  vars_files:
  - 'secrets.vault.yml'
  - 'vars.yml'
  roles:
  - nfs_server
#  - backup

- hosts:
  - proxy
  - jupyterhub_nodes
  vars_files:
  - 'secrets.vault.yml'
  - 'vars.yml'
  roles:
  - nfs_client

- hosts: jupyterhub_nodes
  vars_files:
  - 'secrets.vault.yml'
  - 'vars.yml'
  roles:
  - singleuser

- hosts: jupyterhub_host
  vars_files:
  - 'secrets.vault.yml'
  - 'users.vault.yml'
  - 'vars.yml'
  roles:
  - swarm
  - jupyterhub
#  - cull
#  - stats
