---
- name: add nginx repository
  apt_repository: repo='ppa:nginx/stable' state=present
  register: ppastable
  tags:
    - proxy

- name: install nginx
  apt: pkg=nginx state=installed update_cache=true
  when: ppastable | success
  register: nginxinstalled
  notify:
    - start nginx
  tags:
    - proxy

- name: install php5-fpm
  apt: pkg=php5-fpm state=installed
  tags:
    - proxy

- name: configuration directories
  file: state=directory dest=/etc/nginx mode=0755
  sudo: yes
  tags:
    - proxy

- name: create ssl certs directories
  file: state=directory dest=/etc/nginx/certs mode=0600
  sudo: yes
  tags:
    - proxy

- name: SSL credentials
  template: src={{ item.from }} dest={{ item.to }} mode=0644
  with_items:
  - from: ssl.key.j2
    to: "{{ ssl_key_path }}"
  - from: ssl.crt.j2
    to: "{{ ssl_cert_path }}"
  sudo: yes
  tags:
    - proxy

- name: nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0644
  sudo: yes
  notify:
    - restart nginx
  tags:
    - proxy

