---
- fail: msg="configproxy_auth_token is not defined"
  when: configproxy_auth_token == ''
- fail: msg="cookie_secret is not defined"
  when: cookie_secret == ''
- fail: msg="github_client_id is not defined"
  when: github_client_id == ''
- fail: msg="github_client_secret is not defined"
  when: github_client_secret == ''
- fail: msg="oauth_callback_url is not defined"
  when: oauth_callback_url == ''
- fail: msg="instructor list is empty"
  when: instructors|length == 0

#- name: iptables configuration
#  command: iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to 8000
#  sudo: yes
#

- name: install npm
  apt: name=npm state=latest
  sudo: yes
  
- name: install nodejs-legacy
  apt: name=nodejs-legacy state=latest
  sudo: yes

- name: install configurable-http-proxy
  npm: name=configurable-http-proxy global=yes state=latest
  sudo: yes

- name: stop jupyterhub server
  shell: pgrep -f jupyterhub | xargs -r kill
  ignore_errors: True
  sudo: yes
  tags:
    - launch-jupyterhub

- name: create the jupyterhub_db directory
  file: path=/srv/jupyterhub_db state=directory
  sudo: yes
  tags:
    - docker-rebuild

- name: create jupyterhub.sqlite
  file: path=/srv/jupyterhub_db/jupyterhub.sqlite state=touch mode=0600
  sudo: yes
  tags:
    - docker-rebuild

- name: create the jupyterhub directory
  file: path=/srv/jupyterhub state=directory
  sudo: yes
  tags:
    - docker-rebuild
    - launch-jupyterhub

- name: copy requirements.txt
  copy:
    src:  requirements.txt
    dest: /tmp/requirements.txt
  sudo: yes

- name: install requirements
  pip: requirements=/tmp/requirements.txt executable=pip3
  sudo: yes

- name: install ipython notebook
  pip: name=ipython[notebook] executable=pip3
  sudo: yes

- name: install jupyterhub
  pip: name='git+https://github.com/jupyter/jupyterhub.git@master#egg=jupyterhub' executable=pip3
  sudo: yes

- name: copy jupyterhub_config.py to the jupyterhub directory
  template:
    src: jupyterhub_config.py
    dest: /srv/jupyterhub/jupyterhub_config.py
  sudo: yes
  tags:
    - docker-rebuild
    - launch-jupyterhub

- name: create the userlist
  template: src=userlist.j2 dest=/srv/jupyterhub/userlist
  sudo: yes
  tags:
    - docker-rebuild
    - launch-jupyterhub

- name: create the cookie secret file
  template: src=cookie_secret_file.j2 dest=/srv/jupyterhub/cookie_secret_file
  sudo: yes
  tags:
    - docker-rebuild
    - launch-jupyterhub

- name: add dockerspawner
  pip: name='git+git://github.com/jupyter/dockerspawner.git@master#egg=dockerspawner' executable=pip3
  sudo: yes

- name: add oauthenticator
  pip: name='git+git://github.com/jupyter/oauthenticator.git@master#egg=oauthenticator' executable=pip3
  sudo: yes

- name: add swarmspawner.py
  copy: src=swarmspawner.py dest=/usr/local/lib/python3.4/dist-packages/swarmspawner.py
  sudo: yes
  tags:
    - docker-rebuild
    - swarmspawner

- name: environment variables necessary for Docker Swarm
  lineinfile: dest=/root/.bashrc line="export DOCKER_HOST=https://127.0.0.1:2376"
  sudo: yes

- name: source .bashrc
  shell: source /root/.bashrc
  args:
    executable: /bin/bash
  sudo: yes

- name: launch jupyterhub
  command: /usr/local/bin/jupyterhub --config '/srv/jupyterhub/jupyterhub_config.py' --log-file '/srv/jupyterhub/jupyterhub.log'
  async: 3600
  poll: 0
  sudo: yes
  tags:
    - launch-jupyterhub
    - launch
