---
- name: stop and remove running singleuser containers
  docker:
    docker_api_version: "{{ docker_api_version }}"
    state: absent
    image: edwardjkim/singleuser
  sudo: yes
  tags:
    - singleuser

- name: create the singleuser directory
  file: path=/srv/singleuser state=directory
  sudo: yes
  tags:
    - singleuser
    - docker-rebuild

- name: copy the Dockerfile to the singleuser directory
  copy:
    src: Dockerfile
    dest: /srv/singleuser/Dockerfile
  sudo: yes
  tags:
    - singleuser
    - docker-rebuild

- name: copy singleuser.sh to the singleuser directory
  copy:
    src: singleuser.sh
    dest: /srv/singleuser/singleuser.sh
  sudo: yes
  tags:
    - singleuser
    - docker-rebuild

- name: build edwardjkim/singleuser image
  shell: docker build -t edwardjkim/singleuser /srv/singleuser
  sudo: yes
  tags:
    - singleuser
    - docker-rebuild

