---
- name: python
  apt: name=python state=latest
  sudo: yes

- name: pip install script
  get_url: dest=/tmp/get_pip.py url=https://bootstrap.pypa.io/get-pip.py

- name: pip
  command: python /tmp/get_pip.py creates=/usr/local/bin/pip
  sudo: yes

- name: pip3
  apt: name=python3-pip state=latest
  sudo: yes

- name: pip3 upgrade
  pip: name=pip state=latest executable=pip3
  sudo: yes
